name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 4.0.2
homepage: https://github.com/sbis04/video_trimmer
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.2
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/EyeswingAdmin/ffmpeg_kit_flutter.git
      ref: main
  path_provider: ^2.1.1
  intl: ^0.20.0
  path: ^1.9.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:
